interface Event {
  id: string;
  name: string;
  bettable: boolean;
  state: string;
  type: string;
  type_domain: string;
  type_scope: string;
  start_datetime: string;
  last_modified: string;
  parent_id?: string;
  children?: Event[];
}

const mockEvents: Event[] = [
  {
    id: "e1",
    name: "Football",
    bettable: false,
    state: "new",
    type: "top_level_event",
    type_domain: "football",
    type_scope: "root",
    start_datetime: "2024-07-01T12:00:00Z",
    last_modified: "2024-06-01T12:00:00Z",
    children: [
      {
        id: "e2",
        name: "Premier League",
        bettable: false,
        state: "new",
        type: "category",
        type_domain: "football",
        type_scope: "category",
        start_datetime: "2024-07-01T12:00:00Z",
        last_modified: "2024-06-01T12:00:00Z",
        parent_id: "e1",
        children: [
          {
            id: "e3",
            name: "Man Utd vs Chelsea",
            bettable: true,
            state: "upcoming",
            type: "football_match",
            type_domain: "football",
            type_scope: "single_event",
            start_datetime: "2024-07-01T15:00:00Z",
            last_modified: "2024-06-10T12:00:00Z",
            parent_id: "e2",
          },
          {
            id: "e4",
            name: "Liverpool vs Arsenal",
            bettable: true,
            state: "upcoming",
            type: "football_match",
            type_domain: "football",
            type_scope: "single_event",
            start_datetime: "2024-07-01T18:00:00Z",
            last_modified: "2024-06-11T12:00:00Z",
            parent_id: "e2",
          },
        ],
      },
      {
        id: "e5",
        name: "La Liga",
        bettable: false,
        state: "new",
        type: "category",
        type_domain: "football",
        type_scope: "category",
        start_datetime: "2024-07-02T12:00:00Z",
        last_modified: "2024-06-01T12:00:00Z",
        parent_id: "e1",
        children: [
          {
            id: "e6",
            name: "Barcelona vs Real Madrid",
            bettable: true,
            state: "upcoming",
            type: "football_match",
            type_domain: "football",
            type_scope: "single_event",
            start_datetime: "2024-07-02T15:00:00Z",
            last_modified: "2024-06-10T12:00:00Z",
            parent_id: "e5",
          },
          {
            id: "e7",
            name: "Atletico Madrid vs Sevilla",
            bettable: true,
            state: "upcoming",
            type: "football_match",
            type_domain: "football",
            type_scope: "single_event",
            start_datetime: "2024-07-02T18:00:00Z",
            last_modified: "2024-06-11T12:00:00Z",
            parent_id: "e5",
          },
        ],
      },
    ],
  },
  {
    id: "e8",
    name: "Boxing",
    bettable: false,
    state: "new",
    type: "top_level_event",
    type_domain: "boxing",
    type_scope: "root",
    start_datetime: "2024-07-03T12:00:00Z",
    last_modified: "2024-06-01T12:00:00Z",
    children: [
      {
        id: "e9",
        name: "Heavyweight Championship",
        bettable: false,
        state: "new",
        type: "category",
        type_domain: "boxing",
        type_scope: "category",
        start_datetime: "2024-07-03T12:00:00Z",
        last_modified: "2024-06-01T12:00:00Z",
        parent_id: "e8",
        children: [
          {
            id: "e10",
            name: "Fury vs Uzyk",
            bettable: true,
            state: "upcoming",
            type: "boxing_match",
            type_domain: "boxing",
            type_scope: "single_event",
            start_datetime: "2024-07-03T15:00:00Z",
            last_modified: "2024-06-10T12:00:00Z",
            parent_id: "e9",
          },
          {
            id: "e11",
            name: "Joshua v Wilder",
            bettable: true,
            state: "upcoming",
            type: "boxing_match",
            type_domain: "boxing",
            type_scope: "single_event",
            start_datetime: "2024-07-03T18:00:00Z",
            last_modified: "2024-06-11T12:00:00Z",
            parent_id: "e9",
          },
        ],
      },
    ],
  },
  {
    id: "e12",
    name: "Baseball",
    bettable: false,
    state: "new",
    type: "top_level_event",
    type_domain: "baseball",
    type_scope: "root",
    start_datetime: "2024-07-04T12:00:00Z",
    last_modified: "2024-06-01T12:00:00Z",
    children: [
      {
        id: "e13",
        name: "Major League Baseball",
        bettable: false,
        state: "new",
        type: "category",
        type_domain: "baseball",
        type_scope: "category",
        start_datetime: "2024-07-04T12:00:00Z",
        last_modified: "2024-06-01T12:00:00Z",
        parent_id: "e12",
        children: [
          {
            id: "e14",
            name: "New York Mets vs Texas Rangers",
            bettable: true,
            state: "upcoming",
            type: "baseball_match",
            type_domain: "baseball",
            type_scope: "single_event",
            start_datetime: "2024-07-04T15:00:00Z",
            last_modified: "2024-06-10T12:00:00Z",
            parent_id: "e13",
          },
          {
            id: "e15",
            name: "Chicago Cubs vs Miami Marlins",
            bettable: true,
            state: "upcoming",
            type: "baseball_match",
            type_domain: "baseball",
            type_scope: "single_event",
            start_datetime: "2024-07-04T18:00:00Z",
            last_modified: "2024-06-11T12:00:00Z",
            parent_id: "e13",
          },
        ],
      },
    ],
  },
  {
    id: "e16",
    name: "Basketball",
    bettable: false,
    state: "new",
    type: "top_level_event",
    type_domain: "basketball",
    type_scope: "root",
    start_datetime: "2024-07-05T12:00:00Z",
    last_modified: "2024-06-01T12:00:00Z",
    children: [
      {
        id: "e17",
        name: "NBA",
        bettable: false,
        state: "new",
        type: "category",
        type_domain: "basketball",
        type_scope: "category",
        start_datetime: "2024-07-05T12:00:00Z",
        last_modified: "2024-06-01T12:00:00Z",
        parent_id: "e16",
        children: [
          {
            id: "e18",
            name: "Lakers vs Warriors",
            bettable: true,
            state: "upcoming",
            type: "basketball_match",
            type_domain: "basketball",
            type_scope: "single_event",
            start_datetime: "2024-07-05T15:00:00Z",
            last_modified: "2024-06-10T12:00:00Z",
            parent_id: "e17",
          },
          {
            id: "e19",
            name: "Celtics vs Knicks",
            bettable: true,
            state: "upcoming",
            type: "basketball_match",
            type_domain: "basketball",
            type_scope: "single_event",
            start_datetime: "2024-07-05T18:00:00Z",
            last_modified: "2024-06-11T12:00:00Z",
            parent_id: "e17",
          },
        ],
      },
    ],
  },
];

export type { Event };
export { mockEvents };
